### ISSUE TITLE
Create a new topic for the Sketch plugin

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/indigo-design-docfx#255]
Create and draft a new topic explaining how the Sketch plugin works in terms of the functionality it provides for Theming and Publishing/Syncing prototypes with the Indigo.Design Cloud.

**Comment by DaniMarinov** [comment]
I suggest the following improvements:
- ESC button to close the plugin modal; if the user is in the middle of adding new theme or editing existing one, then it is preferable to have another pop-up asking for Confirmation, for example: 
![plugin](https://user-images.githubusercontent.com/41998471/51390581-6057dc00-1b38-11e9-9472-01a5380ae471.png)
- I recommend adding a tooltip over the main color to indicate that it editable, because now there isn't set any hover or other indication
![tooltip](https://user-images.githubusercontent.com/41998471/51390940-6ac6a580-1b39-11e9-85cf-bc1b8579ac33.png)
- I recommend having scroll all the time, not only when it is being used, in order to indicate that there are content below to be edited
<img width="1440" alt="screen shot 2019-01-18 at 3 57 08 pm" src="https://user-images.githubusercontent.com/41998471/51391065-bed18a00-1b39-11e9-8276-d6299d818973.png">
- It would be great to have loading indicator here
<img width="840" alt="screen shot 2019-01-18 at 4 06 21 pm" src="https://user-images.githubusercontent.com/41998471/51391550-0c9ac200-1b3b-11e9-9ae3-447af238a748.png">
